language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jeangu2002/docker-react -f Dockerfile.dev .

script:
  # docker run -e CI=true USERNAME/docker-react npm run test
  - docker run -e CI=true jeangu2002/docker-react npm run test
